services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
    depends_on:
      - db
